In [1]:
import numpy as np

In [3]:
sample_matrix=np.array([[1,2,3,4],[4,3,2,1],[8,7,6,5],[5,6,7,8]])  
sample_matrix

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [8, 7, 6, 5],
       [5, 6, 7, 8]])

In [4]:
sample_matrix=np.array([1,2,3,4],[4,3,2,1],[8,7,6,5],[5,6,7,8])  
sample_matrix

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [6]:
sample_matrix[2][3] #index always starts from 0; essentially 3rd row and 4th col intersection index's element

np.int64(5)

In [29]:
sample_matrix=np.array([[15,20,1,23],[24,23,21,33],[56,76,24,7]])  
sample_matrix

array([[15, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [30]:
sample_matrix[2][3] #index always starts from 0; essentially 3rd row and 4th col intersection index's element

np.int64(7)

In [31]:
sample_matrix[2,:] #3rd row; all columns 

array([56, 76, 24,  7])

In [32]:
sample_matrix[2]  #3rd row; all columns

array([56, 76, 24,  7])

In [33]:
sample_matrix[:,(3,2)]   #all rows; (3,2) cols -> 3rd col and the 2nd col

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [34]:
sample_matrix[:,(2,3)]

array([[ 1, 23],
       [21, 33],
       [24,  7]])

In [35]:
#if the desired o/p is 33 what shld be the code
#method1
sample_matrix[1][3]

np.int64(33)

In [36]:
#method2
sample_matrix[1,3]

np.int64(33)

In [38]:
#if the desired o/p is 1 and 21 what shld be the code
sample_matrix[(0,1),2]

array([ 1, 21])

In [40]:
sample_matrix[0:2,2]

array([ 1, 21])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

In [42]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [43]:
sample_matrix=np.arange(1,21)

In [44]:
sample_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
sample_matrix+sample_matrix
sample_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
np.exp(sample_matrix)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [47]:
np.sqrt(sample_matrix)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [48]:
np.log(sample_matrix)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [50]:
np.min(sample_matrix)

np.int64(1)

In [51]:
np.max(sample_matrix)

np.int64(20)

In [52]:
np.argmax(sample_matrix)

np.int64(19)

In [53]:
np.argmin(sample_matrix)

np.int64(0)

In [54]:
np.square(sample_matrix)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [55]:
np.std(sample_matrix)

np.float64(5.766281297335398)

In [56]:
np.var(sample_matrix)

np.float64(33.25)

In [57]:
np.mean(sample_matrix)

np.float64(10.5)

In [59]:
array=np.random.randn(3,4) #normal distribution
array

array([[ 1.26019305, -0.11879118,  0.46589052, -0.16346927],
       [ 0.82414263, -0.21123769,  0.7216653 ,  0.15599962],
       [ 0.05323249,  3.16910545,  0.56989191,  0.12197766]])

In [60]:
np.round(array,decimals=3)

array([[ 1.26 , -0.119,  0.466, -0.163],
       [ 0.824, -0.211,  0.722,  0.156],
       [ 0.053,  3.169,  0.57 ,  0.122]])

In [62]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
sports

array(['golf', 'cricket', 'fball', 'cricket', 'fball', 'basketball'],
      dtype='<U10')

In [64]:
np.unique(sports) # dtype='<U10'  -> maximum characters

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')