In [1]:
import numpy as np

In [5]:
# difference between the numbers will be constant;
# linspace -> linearly spaced
# (0, 20, 8) -> 8 numbers starting from 0 until 20 

In [6]:
np.linspace(0,1,5)        #linearly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [9]:
np.eye(3)      #identity matrix of size 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Uniform distribution
### Numbers will be ranging between 0 to 1

In [10]:
np.random.rand(3,2)         #3rows; 2Cols; 

array([[0.84260374, 0.54539311],
       [0.60286155, 0.63760316],
       [0.71906307, 0.1913337 ]])

### Normal distribution

In [13]:
np.random.randint(34,100,50)

array([65, 62, 54, 64, 63, 39, 71, 82, 43, 77, 51, 81, 36, 54, 36, 58, 98,
       93, 70, 40, 64, 62, 48, 47, 49, 45, 66, 66, 54, 70, 50, 70, 93, 97,
       92, 92, 88, 45, 85, 45, 34, 38, 61, 87, 51, 71, 82, 39, 92, 37],
      dtype=int32)

### picks a random int no. from within the given range

In [20]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
sample_array.reshape(6,5)            #reshape sample_array to 6 rows and 5 cols

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [25]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [33]:
sample_array.dtype

dtype('int64')

In [28]:
sample_array.reshape(4,7)        #when we mul the no of rows n cols if shld always be equal to the total no of elements, else error

ValueError: cannot reshape array of size 30 into shape (4,7)

In [17]:
np.random.randint(34,100,50)

array([66, 45, 39, 44, 70, 76, 57, 81, 95, 67, 81, 87, 79, 42, 76, 56, 61,
       69, 74, 70, 83, 90, 94, 34, 90, 42, 43, 38, 85, 56, 56, 82, 55, 55,
       69, 84, 66, 37, 94, 64, 83, 37, 74, 85, 38, 50, 49, 82, 36, 43],
      dtype=int32)

In [16]:
np.random.randint(34,100)   #34 can come; 100 cannot; essentially, 34 to 99

78

In [18]:
np.random.randint(0,100,5)

array([67, 41, 78, 74, 71], dtype=int32)

In [22]:
rand_array=np.random.randint(0,100,20)
rand_array

array([36, 96, 74, 36, 26,  7, 97, 51, 16, 89,  7, 23, 22, 20, 56, 53, 27,
       71, 44, 78], dtype=int32)

In [19]:
np.random.randint(1,100,1)

array([84], dtype=int32)

In [12]:
np.random.randn(3,2)           #n->negative

array([[ 0.34763595, -1.12520222],
       [ 1.32510164,  2.77443894],
       [ 0.1679761 ,  2.22252477]])

In [30]:
rand_array.min()   #minimum value in the list rand_array

np.int32(7)

In [31]:
rand_array.argmin()        #index of the minimum value

np.int64(5)

In [35]:
a=np.eye(5)          #identity matrix of size 5x5
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a.T             #identity, diagonal matrix -> transpose -> identity, diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a=np.random.rand(2,3) #uniform distribution -> range of numbers -> 0 to 1

In [39]:
a

array([[0.88744474, 0.23851123, 0.57867451],
       [0.54644867, 0.80679416, 0.98194444]])

In [40]:
a.T

array([[0.88744474, 0.54644867],
       [0.23851123, 0.80679416],
       [0.57867451, 0.98194444]])

In [42]:
sample_array=np.arange(10,21)    # range-> 10 to 20

In [43]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[3]

np.int64(13)

In [46]:
sample_array[3:7]    #index 3,4,5,6 elements

array([13, 14, 15, 16])

In [47]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [49]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [50]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [51]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [52]:
subset_sample_array[1:4]=100
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])